---
# Source: my-flask-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-my-flask-app
  labels:
    helm.sh/chart: my-flask-app-0.1.0
    app.kubernetes.io/name: my-flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: my-flask-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-my-flask-app
  labels:
    helm.sh/chart: my-flask-app-0.1.0
    app.kubernetes.io/name: my-flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-flask-app
    app.kubernetes.io/instance: release-name
---
# Source: my-flask-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-my-flask-app
  labels:
    helm.sh/chart: my-flask-app-0.1.0
    app.kubernetes.io/name: my-flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-flask-app
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: my-flask-app-0.1.0
        app.kubernetes.io/name: my-flask-app
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-my-flask-app
      securityContext:
        {}
      containers:
        - name: my-flask-app
          securityContext:
            {}
          image: "bvcelari/my-flask-app:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          resources:
            {}
